# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"app": "01_cli.ipynb",
         "create": "01_cli.ipynb",
         "register": "01_cli.ipynb",
         "verify": "01_cli.ipynb",
         "document": "01_cli.ipynb",
         "main": "01_cli.ipynb",
         "create_data_model": "02_create_environment.ipynb",
         "create_folders": "02_create_environment.ipynb",
         "create_config": "02_create_environment.ipynb",
         "create_environment": "02_create_environment.ipynb",
         "BaseModel": "03_data_model.ipynb",
         "Base": "03_data_model.ipynb",
         "tag_link_table": "03_data_model.ipynb",
         "Tag": "03_data_model.ipynb",
         "Data_Group": "03_data_model.ipynb",
         "Delivery": "03_data_model.ipynb",
         "Raw_Data": "03_data_model.ipynb",
         "Dataset": "03_data_model.ipynb",
         "DataIntakeEnv": "04_environment.ipynb",
         "sync_data_folder": "05_receipt.ipynb",
         "sync_data_group": "05_receipt.ipynb",
         "sync_receipt": "05_receipt.ipynb",
         "write_receipt": "05_receipt.ipynb",
         "parse_receipt": "05_receipt.ipynb",
         "extract_delivery_from_script": "06_registration.ipynb",
         "register_data_group": "06_registration.ipynb",
         "register_data_folder": "06_registration.ipynb",
         "register_all": "06_registration.ipynb",
         "check_datagroup": "07_verification.ipynb",
         "hash_files": "99_utils.ipynb",
         "process_data_group": "99_utils.ipynb",
         "count_data_group_components": "99_utils.ipynb",
         "Data_Groups_Type": "99_utils.ipynb"}

modules = ["cli.py",
           "create_environment.py",
           "data_model.py",
           "environment.py",
           "receipt.py",
           "registration.py",
           "verification.py",
           "utils.py"]

doc_url = "https://JorickvdHoeven.github.io/drt/drt/"

git_url = "https://github.com/JorickvdHoeven/drt/tree/master/"

def custom_doc_links(name): return None
